-- PDB 컨텍스트로 전환
ALTER SESSION SET CONTAINER=ORCL;

-- DEV_USER 계정 생성 (비밀번호: DevUser2025)
CREATE USER DEV_USER IDENTIFIED BY "DevUser2025";

-- 데이터베이스 접속 및 객체 생성을 위한 권한 부여
GRANT CREATE SESSION TO DEV_USER;
GRANT CREATE TABLE TO DEV_USER;
GRANT CREATE VIEW TO DEV_USER;
GRANT CREATE PROCEDURE TO DEV_USER;
GRANT CREATE SEQUENCE TO DEV_USER;
GRANT CREATE TRIGGER TO DEV_USER;

-- 테이블스페이스 사용 권한 부여
ALTER USER DEV_USER QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO DEV_USER;