server:
  port: 8081
spring:
  application:
    name: dasom-api
  profiles:
    active: credentials # 추가 (제외시키면 application-credentials.yml 못 찾음)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
springdoc:
  swagger-ui:
    path: /api/swagger-ui
  api-docs:
    path: /api/v1/api-docs
